# Environment for CoderingsTool

name: coderings_tool
channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.9
  
  # Data processing (conda packages)
  - pandas=2.2.3
  - numpy=1.26.4
  - scikit-learn=1.5.2
  
  # SPSS file reading
  - pyreadstat=1.2.7
  
  # ML/Clustering (conda packages)  
  - hdbscan=0.8.39
  - umap-learn=0.5.7
  
  # Async support
  - nest-asyncio=1.6.0
  
  # Progress bars and widgets
  - tqdm=4.67.0
  - ipywidgets=8.1.5
  - jupyter=1.1.1
  
  # Build tools
  - pip
  
  # pip packages (exact versions from your environment)
  - pip:
    # Data models
    - pydantic==2.10.4
    - pydantic-core==2.27.2
    
    # Web interface
    - streamlit==1.40.1
    
    # NLP
    - spacy==3.7.6
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    
    # LangChain
    - langchain-core==0.3.29
    - langchain-openai==0.2.14
    
    # OpenAI & LLM
    - openai==1.59.3
    - instructor==1.7.9
    - tiktoken==0.8.0
    
    # Python 3.9 compatibility for instructor
    - eval_type_backport
    
    # Language models (only what you need)
    - https://github.com/explosion/spacy-models/releases/download/nl_core_news_lg-3.7.0/nl_core_news_lg-3.7.0-py3-none-any.whl
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.7.1/en_core_web_lg-3.7.1-py3-none-any.whl

# Post-install setup:
# 1. Set environment variable: export OPENAI_API_KEY="your-key"
# 2. Verify spaCy models: python -c "import spacy; print(spacy.info())"

# Installation instructions:
# 1. conda env create -f environment.yml
# 2. conda activate codings
# 3. python -m spacy download nl_core_news_lg
# 4. python -m spacy download en_core_web_lg

