#%%
"""
Debug script for Step 2: Full LLM Request Inspector
Shows exactly what the LLM receives: prompt text + instructor-generated Pydantic schema.

Loads saved prompts from exports/prompts/step2_*.json (generated by run_qualityFilter.py).
Falls back to building a sample prompt if no saved prompts exist.

Usage:
    cd src && python -m pipeline.step_2_qualityFilter.debug_full_prompts
"""

import sys
import json
from pathlib import Path
from typing import Optional

src_dir = Path(__file__).parent.parent.parent
project_root = src_dir.parent
sys.path.insert(0, str(src_dir))

from utils.cacheManager import generate_enhanced_variable_key
from test_data import TEST_DATA
from pipeline.step_2_qualityFilter.prompts_qualityFilter import (
    GRADER_INSTRUCTIONS_NANO,
    GRADER_INSTRUCTIONS_STRUCTURED,
    QualityFilterStructuredResponse,
)
from pipeline.step_2_qualityFilter.config_qualityFilter import DEFAULT_QUALITY_FILTER_CONFIG
from config import DEFAULT_LANGUAGE

# Configuration
FILENAME = TEST_DATA.filename
VAR_NAME = TEST_DATA.var_name
SAMPLE_SIZE = TEST_DATA.sample_size


# =============================================================================
# Prompt Type → Response Model Mapping
# =============================================================================

PROMPT_MODELS = {
    "quality_assessment": QualityFilterStructuredResponse,
}


# =============================================================================
# File Loading
# =============================================================================

def get_prompts_file() -> Path:
    variable_key = generate_enhanced_variable_key([VAR_NAME], False, SAMPLE_SIZE)
    prompts_dir = project_root / "exports" / "prompts"
    return prompts_dir / f"step2_{VAR_NAME}_{variable_key}.json"


def load_prompts(filepath: Path) -> Optional[dict]:
    if not filepath.exists():
        return None
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)


# =============================================================================
# Display: saved prompt entry
# =============================================================================

def print_full_prompt(prompt_entry: dict, index: int, total: int) -> None:
    prompt_type = prompt_entry.get("prompt_type", "unknown")

    print(f"\n{'='*100}")
    print(f"PROMPT {index}/{total}: {prompt_type}")
    print(f"{'='*100}")

    metadata = prompt_entry.get("metadata", {})
    print(f"Step:     {prompt_entry.get('step_name', 'unknown')}")
    if "model" in metadata:
        print(f"Model:    {metadata['model']}")
    if "language" in metadata:
        print(f"Language: {metadata['language']}")
    if "var_lab" in metadata:
        print(f"Question: {metadata['var_lab']}")

    # Prompt content
    content = prompt_entry.get("prompt_content", "(no content)")
    print(f"\n[Prompt Content] ({len(content):,} chars, ~{len(content)//4:,} tokens)")
    print("-" * 100)
    print(content)
    print("-" * 100)

    # Response model schema
    model = PROMPT_MODELS.get(prompt_type)
    is_nano = "nano" in metadata.get("model", "").lower()

    print(f"\n[Response Model]")
    if is_nano:
        print("  Pattern A (nano): raw text with <scratchpad>/<category> XML tags — no Pydantic model")
    elif model is not None:
        print(f"  Pattern B (instructor): {model.__name__}")
        try:
            schema = model.model_json_schema()
            schema_str = json.dumps(schema, indent=2)
            print(f"\n[JSON Schema (what instructor injects as tool definition)]")
            print("-" * 100)
            print(schema_str)
            print("-" * 100)
            print(f"  Schema: {len(schema_str):,} chars (~{len(schema_str)//4:,} tokens)")
        except Exception as e:
            print(f"  ERROR generating schema: {e}")
    else:
        print(f"  Unknown prompt type: {prompt_type}")

    # Stats
    print(f"\n[Stats]")
    print(f"  Prompt: {len(content):,} chars (~{len(content)//4:,} tokens)")


# =============================================================================
# Fallback: build sample prompts when no saved file exists
# =============================================================================

def show_sample_prompts(var_lab: str) -> None:
    model = DEFAULT_QUALITY_FILTER_CONFIG.model
    is_nano = "nano" in model.lower()
    template = GRADER_INSTRUCTIONS_NANO if is_nano else GRADER_INSTRUCTIONS_STRUCTURED

    print(f"\nModel:    {model} ({'nano/Pattern A' if is_nano else 'Pattern B/instructor'})")

    samples = [
        ("Meaningful", "De sfeer was geweldig en de muziek was top."),
        ("Don't know", "Weet ik niet"),
        ("Gibberish", "asdfkj jjjjj"),
        ("Empty", ""),
    ]

    for label, response_text in samples:
        prompt = template.format(
            language=DEFAULT_LANGUAGE,
            var_lab=var_lab,
            response_text=response_text,
        )
        print(f"\n{'='*100}")
        print(f"SAMPLE: {label}  —  \"{response_text}\"")
        print(f"{'='*100}")
        print(f"\n[Prompt Content] ({len(prompt):,} chars, ~{len(prompt)//4:,} tokens)")
        print("-" * 100)
        print(prompt)
        print("-" * 100)

    # Show response model schema (Pattern B only)
    if not is_nano:
        print(f"\n{'='*100}")
        print("RESPONSE MODEL (Pydantic schema injected by instructor)")
        print(f"{'='*100}")
        try:
            schema = QualityFilterStructuredResponse.model_json_schema()
            schema_str = json.dumps(schema, indent=2)
            print(f"\n[JSON Schema]")
            print("-" * 100)
            print(schema_str)
            print("-" * 100)
            print(f"  Schema: {len(schema_str):,} chars (~{len(schema_str)//4:,} tokens)")
        except Exception as e:
            print(f"  ERROR generating schema: {e}")


# =============================================================================
# Main
# =============================================================================

def main():
    prompts_file = get_prompts_file()

    print("=" * 100)
    print("DEBUG: Step 2 - Full LLM Request Inspector")
    print("Shows prompt text + Pydantic response model schemas (as seen by instructor)")
    print("=" * 100)
    print(f"Variable:     {VAR_NAME}")
    print(f"Sample size:  {SAMPLE_SIZE}")
    print(f"Prompts file: {prompts_file}")
    print("=" * 100)

    # Try loading saved prompts first
    data = load_prompts(prompts_file)

    if data is not None:
        print(f"\nSession ID:    {data.get('session_id', 'unknown')}")
        print(f"Capture time:  {data.get('capture_time', 'unknown')}")
        print(f"Total prompts: {data.get('total_prompts', 0)}")

        summary = data.get("summary", {})
        if summary:
            print("\n[Prompts by Step]")
            for step, count in summary.get("by_step", {}).items():
                print(f"  {step}: {count}")

        prompts = data.get("prompts", [])
        if prompts:
            print(f"\n{'#'*100}")
            print(f"# FULL LLM REQUEST DETAILS ({len(prompts)} prompts)")
            print(f"{'#'*100}")
            for i, entry in enumerate(prompts, 1):
                print_full_prompt(entry, i, len(prompts))
        else:
            print("\nNo prompts found in file.")
    else:
        print(f"\nNo saved prompts found at: {prompts_file}")
        print("Run step 2 first to generate:")
        print("  cd src && python -m pipeline.step_2_qualityFilter.run_qualityFilter")
        print("\nShowing sample prompts from template instead...")

        from utils import dataLoader
        data_dir = project_root / "data"
        loader = dataLoader.DataLoader(data_dir=str(data_dir), verbose=False)
        var_lab = loader.get_varlab(filename=FILENAME, var_name=VAR_NAME)
        print(f"Question:     {var_lab}")

        show_sample_prompts(var_lab)


if __name__ == "__main__":
    main()
