"""
Step 6: Code Assigner — Code Assignment Pipeline (P10)

Assigns each idea to exactly one MECE code from the codebook
generated by step 5.

Usage:
    cd src && python -m steps.step_6_codeAssigner.run_codeAssigner
"""
